import * as THREE from 'three';
import {OrbitControls} from './OrbitControls.js';
const $=id=>document.getElementById(id), fmt=(n,d=2)=>n==null?'—':n.toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer,scene,camera,controls,stars=[],selected=null,starMesh,selectionRing,plane,labels=[],showNames=true,transition=null,mode='orbit',frameId,dragStart=null,dragged=false,animationTime=0;
const fitFactor=()=>Math.max(1,.78/(innerWidth/innerHeight));
let lastFit=fitFactor();
const homePosition=new THREE.Vector3(33,28,42), origin=new THREE.Vector3(), projected=new THREE.Vector3(), pointer=new THREE.Vector2(), positions=[];
const colour=s=>s.id==='sun'?'#ffe1a3':s.kind.startsWith('WD')?'#bfdcff':s.spectral?.startsWith('A')?'#d6e8ff':s.spectral?.startsWith('F')?'#f3f3e5':s.spectral?.startsWith('G')?'#f3dfb4':s.spectral?.startsWith('K')?'#e9bb94':s.spectral?'#cf927e':'#c6caca';
function line(a,b,color=0x36535a,opacity=.4){return new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]),new THREE.LineBasicMaterial({color,transparent:true,opacity,depthWrite:false}));}
function createPlane(){const g=new THREE.Group();for(let i=-20;i<=20;i++){const end=Math.sqrt(400-i*i);if(!end)continue;const major=i%5===0;g.add(line([i,0,-end],[i,0,end],major?0x718e96:0x4c686f,major?.55:.32));g.add(line([-end,0,i],[end,0,i],major?0x718e96:0x4c686f,major?.55:.32));}for(let r=5;r<=20;r+=5){const pts=[];for(let i=0;i<=256;i++){const t=i/256*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(t)*r,0,Math.sin(t)*r));}g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:r===20?0x9cb9c1:0x7f9da6,transparent:true,opacity:r===20?.8:.65})));}g.add(line([-21.8,0,0],[21.8,0,0],0x759499,.65));g.add(line([0,0,-21.8],[0,0,21.8],0x759499,.65));for(let i=0;i<120;i++){const t=i*Math.PI/60,r=20,rr=i%5?20.15:20.4;g.add(line([r*Math.cos(t),0,r*Math.sin(t)],[rr*Math.cos(t),0,rr*Math.sin(t)],0x7c9499,.6));}const desc=[];for(const r of [5,10,15,20])desc.push({text:r+' AL',p:new THREE.Vector3(r,0,.6)});desc.push({text:'λ 0°',p:new THREE.Vector3(22.2,0,0)},{text:'λ 90°',p:new THREE.Vector3(0,0,-22.2)});desc.forEach(({text,p})=>{const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');ctx.font='24px Plex, monospace';ctx.fillStyle='#89a7ae';ctx.textAlign='center';ctx.fillText(text,128,40);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,opacity:.8,depthTest:false}));sp.position.copy(p);sp.scale.set(2.7,.675,1);g.add(sp);});return g;}
function setMode(next){mode=next;['orbit','top'].forEach(id=>{$(id).classList.toggle('active',id===next);$(id).setAttribute('aria-pressed',id===next)});}
function moveCamera(pos,target=origin){if(reduced){camera.position.copy(pos);controls.target.copy(target);controls.update();return;}transition={start:performance.now(),from:camera.position.clone(),to:pos.clone(),targetFrom:controls.target.clone(),targetTo:target.clone()};}
function home(){setMode('orbit');moveCamera(homePosition.clone().multiplyScalar(fitFactor()));}
function closeCard(){selected=null;$('star-card').classList.remove('open');$('star-card').setAttribute('aria-hidden','true');$('star-card').inert=true;selectionRing.visible=false;updateRows();}
function fillCard(s){$('card-rank').textContent=`CATALOGO / ${String(s.rank).padStart(3,'0')} — 100`;$('card-name').textContent=s.name;$('card-type').textContent=(s.id==='sun'?'LA NOSTRA STELLA':s.kind.startsWith('WD')?'NANA BIANCA':s.kind.startsWith('LM')?'STELLA DI PICCOLA MASSA':'STELLA')+' · '+(s.spectral||'TIPO NON DISPONIBILE')+(s.kind.includes('?')?' · CLASSIFICAZIONE INCERTA':'');$('card-distance').textContent=fmt(s.distanceLy);$('card-symbol').style.setProperty('--star-color',colour(s));
const g=s.g??s.gEstimated, facts=[['Distanza',fmt(s.distancePc,3)+' pc'],['Tipo spettrale',s.spectral||'Non disponibile'],...(s.id==='sun'?[]:[['Parallasse',fmt(s.parallax,3)+' mas'],['Errore parallasse',s.parallaxError==null?'—':'± '+fmt(s.parallaxError,3)+' mas'],[s.g!=null?'Magnitudine G':'G stimata',fmt(g)],['Indice BP − RP',s.bp!=null&&s.rp!=null?fmt(s.bp-s.rp):'—'],['Velocità radiale',s.rv==null?'—':fmt(s.rv,1)+' km/s'],['Epoca coordinate',fmt(s.epoch,1)]])];$('card-facts').replaceChildren(...facts.flatMap(([k,v])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return[dt,dd];}));
$('card-note').textContent=s.id==='sun'?'Origine del riferimento eliocentrico. Simbolo non in scala.':'ID catalogo: '+s.catalogName+(s.gaiaId?' · Gaia EDR3 '+s.gaiaId:'')+'. '+(s.kind.includes('?')?'Il catalogo indica un tipo stellare incerto. ':'')+'— = dato non disponibile.';
const peers=stars.filter(x=>x.system===s.system&&x.id!==s.id);$('companions').replaceChildren(...peers.map(x=>{const b=document.createElement('button');b.textContent=x.name;b.title='Seleziona la componente '+x.name;b.onclick=()=>select(x);return b;}));$('simbad').href=s.id==='sun'?'https://science.nasa.gov/sun/':'https://simbad.cds.unistra.fr/simbad/sim-id?Ident='+encodeURIComponent(s.catalogName);$('simbad').textContent=s.id==='sun'?'IL SOLE / NASA ↗':'APRI IN SIMBAD ↗';}
function select(s){if(selected?.id===s.id){closeCard();return;}selected=s;fillCard(s);$('star-card').inert=false;$('star-card').setAttribute('aria-hidden','false');$('star-card').classList.add('open');selectionRing.visible=true;selectionRing.position.fromArray(s.position);$('announcement').textContent=s.name+', '+fmt(s.distanceLy)+' anni luce dal Sole';updateRows();if(innerWidth<651){$('catalog-body').hidden=true;$('catalog-toggle').setAttribute('aria-expanded','false');document.querySelector('.plus').textContent='+';}}
function updateRows(){document.querySelectorAll('.star-row').forEach(el=>{const on=el.dataset.id===selected?.id;el.classList.toggle('selected',on);el.setAttribute('aria-pressed',on);});}
function populateList(){const q=$('search').value.trim().toLowerCase();const results=stars.filter(s=>[s.name,s.catalogName,s.commonName,s.gaiaId].some(v=>v?.toLowerCase().includes(q)));$('star-list').replaceChildren(...results.map(s=>{const b=document.createElement('button');b.className='star-row';b.dataset.id=s.id;b.setAttribute('aria-label',s.name+', '+fmt(s.distanceLy)+' anni luce');const n=document.createElement('span'),d=document.createElement('span');n.textContent=s.name;d.textContent=fmt(s.distanceLy);b.append(n,d);b.onclick=()=>select(s);return b;}));$('result-count').textContent=results.length?results.length+' / 100 OGGETTI':'NESSUNA STELLA TROVATA';updateRows();}
function pick(event){const rect=$('space').getBoundingClientRect();let best=null,min=18;stars.forEach((s,i)=>{projected.copy(positions[i]).project(camera);if(projected.z<-1||projected.z>1)return;const x=(projected.x+1)*rect.width/2+rect.left,y=(-projected.y+1)*rect.height/2+rect.top;const dist=Math.hypot(x-event.clientX,y-event.clientY);if(dist<min){min=dist;best=s;}});return best;}
function syncLabels(){const w=innerWidth,h=innerHeight,boxes=[],mobile=w<651;const order=labels.slice().sort((a,b)=>(b.s.id===selected?.id?2:b.s.id==='sun'?1:0)-(a.s.id===selected?.id?2:a.s.id==='sun'?1:0));for(const l of order){const important=l.s.major||l.s.id===selected?.id;projected.copy(l.p).project(camera);const x=(projected.x+1)*w/2,y=(-projected.y+1)*h/2;let visible=showNames&&important&&projected.z>-1&&projected.z<1&&x>25&&x<w-25&&y>145&&y<h-150;const width=l.width,left=x-width/2,top=y+10;const rect=[left,top,left+width,top+22];if(visible&&boxes.some(b=>rect[0]<b[2]+5&&rect[2]>b[0]-5&&rect[1]<b[3]+3&&rect[3]>b[1]-3))visible=false;if(visible&&!mobile&&selected&&x>w-365&&y>140)visible=false;if(visible&&!$('catalog-body').hidden&&x<320&&y>150)visible=false;l.el.hidden=!visible;if(visible){boxes.push(rect);l.el.style.left=x+'px';l.el.style.top=y+'px';l.el.classList.toggle('selected',l.s.id===selected?.id);}}}
function render(now){frameId=requestAnimationFrame(render);const delta=Math.min((now-animationTime)/1000,.05);animationTime=now;if(transition){const t=Math.min(1,(now-transition.start)/950),e=1-Math.pow(1-t,3);camera.position.lerpVectors(transition.from,transition.to,e);controls.target.lerpVectors(transition.targetFrom,transition.targetTo,e);if(t===1)transition=null;}controls.update(delta);if(selectionRing.visible){selectionRing.quaternion.copy(camera.quaternion);const size=camera.position.distanceTo(selectionRing.position)*.018;selectionRing.scale.setScalar(size);}syncLabels();renderer.render(scene,camera);}
function resize(){const fit=fitFactor();camera.position.sub(controls.target).multiplyScalar(fit/lastFit).add(controls.target);lastFit=fit;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);starMesh.material.uniforms.pixelRatio.value=Math.min(devicePixelRatio,2);renderer.setPixelRatio(Math.min(devicePixelRatio,2));}
async function init(){const response=await fetch('./stars.json');if(!response.ok)throw new Error('Impossibile caricare il catalogo.');const data=await response.json();stars=data.stars;await document.fonts.ready;
renderer=new THREE.WebGLRenderer({canvas:$('space'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setClearColor(0x000000,1);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.05,500);camera.position.copy(homePosition).multiplyScalar(fitFactor());controls=new OrbitControls(camera,$('space'));controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=1.8;controls.maxDistance=140;controls.rotateSpeed=.65;controls.zoomSpeed=.75;controls.autoRotateSpeed=.3;controls.addEventListener('start',()=>{transition=null;});controls.addEventListener('end',()=>{if(mode==='top'&&Math.abs(camera.position.x-controls.target.x)>.3)setMode('orbit')});
plane=createPlane();scene.add(plane);const pos=[],col=[],sizes=[];stars.forEach(s=>{const p=new THREE.Vector3(...s.position);positions.push(p);pos.push(...s.position);const c=new THREE.Color(colour(s));col.push(c.r,c.g,c.b);sizes.push(s.id==='sun'?36:s.major?26:19);const el=document.createElement('button');el.className='star-label'+(s.id==='sun'?' sun':'');el.textContent=s.name;el.setAttribute('aria-label','Seleziona '+s.name);el.onclick=()=>select(s);$('labels').append(el);labels.push({s,p,el,width:s.name.length*(innerWidth<651?5.4:6.6)+14});});
const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(col,3));geo.setAttribute('size',new THREE.Float32BufferAttribute(sizes,1));const mat=new THREE.ShaderMaterial({uniforms:{pixelRatio:{value:Math.min(devicePixelRatio,2)}},vertexShader:`attribute float size; varying vec3 vColor; uniform float pixelRatio; void main(){vColor=color;vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=size*pixelRatio*clamp(45.0/-mv.z,0.65,1.65);}`,fragmentShader:`varying vec3 vColor;void main(){vec2 uv=gl_PointCoord-0.5;float d=length(uv);if(d>0.5)discard;float core=1.0-smoothstep(0.055,0.145,d);float glow=exp(-d*8.0)*0.7;float rays=exp(-abs(uv.x)*95.0)*exp(-abs(uv.y)*11.0)+exp(-abs(uv.y)*95.0)*exp(-abs(uv.x)*11.0);gl_FragColor=vec4(mix(vColor,vec3(1.0),core*0.5)*(core+glow+rays*0.2),min(1.0,core+glow));}`,transparent:true,vertexColors:true,depthWrite:false,blending:THREE.AdditiveBlending});starMesh=new THREE.Points(geo,mat);starMesh.renderOrder=3;scene.add(starMesh);
const drops=new THREE.Group();stars.forEach(s=>{if(s.major&&s.id!=='sun')drops.add(line(s.position,[s.position[0],0,s.position[2]],0x52787f,.23));});plane.add(drops);
selectionRing=new THREE.Mesh(new THREE.RingGeometry(.75,.79,64),new THREE.MeshBasicMaterial({color:0xd7e8e8,side:THREE.DoubleSide,transparent:true,opacity:.85,depthTest:false}));selectionRing.visible=false;selectionRing.renderOrder=5;scene.add(selectionRing);
// Small solar reference ring, intentionally symbolic rather than a stellar radius.
const solarRing=new THREE.Mesh(new THREE.RingGeometry(.28,.3,64),new THREE.MeshBasicMaterial({color:0xd7b677,side:THREE.DoubleSide,transparent:true,opacity:.7}));solarRing.rotation.x=-Math.PI/2;scene.add(solarRing);
populateList();$('loading').hidden=true;render(performance.now());window.addEventListener('resize',resize);
$('space').addEventListener('pointerdown',e=>{dragStart=[e.clientX,e.clientY];dragged=false});$('space').addEventListener('pointermove',e=>{if(dragStart&&Math.hypot(e.clientX-dragStart[0],e.clientY-dragStart[1])>5)dragged=true;$('space').style.cursor=dragStart?'grabbing':pick(e)?'pointer':'grab';});$('space').addEventListener('pointerup',e=>{if(!dragged&&e.button===0){const s=pick(e);if(s)select(s);}dragStart=null;});$('space').addEventListener('pointercancel',()=>{dragStart=null;dragged=true});$('space').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key)){e.preventDefault();transition=null;const v=camera.position.clone().sub(controls.target),s=new THREE.Spherical().setFromVector3(v);if(e.key==='ArrowLeft')s.theta-=.1;if(e.key==='ArrowRight')s.theta+=.1;if(e.key==='ArrowUp')s.phi-=.1;if(e.key==='ArrowDown')s.phi+=.1;if(e.key==='+'||e.key==='=')s.radius*=.9;if(e.key==='-')s.radius*=1.1;s.radius=THREE.MathUtils.clamp(s.radius,1.8,140);s.makeSafe();camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));if(e.key==='Home')home();else setMode('orbit');}});
$('home').onclick=home;$('orbit').onclick=home;$('top').onclick=()=>{setMode('top');controls.autoRotate=false;$('rotate').classList.remove('active');$('rotate').setAttribute('aria-pressed','false');moveCamera(new THREE.Vector3(0,55,.01).multiplyScalar(fitFactor()));};$('plane').onclick=()=>{plane.visible=!plane.visible;$('plane').classList.toggle('active',plane.visible);$('plane').setAttribute('aria-pressed',plane.visible);document.querySelector('.axis-note').hidden=!plane.visible;};$('names').onclick=()=>{showNames=!showNames;$('names').classList.toggle('active',showNames);$('names').setAttribute('aria-pressed',showNames)};$('rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('rotate').classList.toggle('active',controls.autoRotate);$('rotate').setAttribute('aria-pressed',controls.autoRotate);if(controls.autoRotate)setMode('orbit');};$('close-card').onclick=closeCard;$('focus-star').onclick=()=>{if(!selected)return;const target=new THREE.Vector3(...selected.position),dir=camera.position.clone().sub(controls.target).normalize().multiplyScalar(13);moveCamera(target.clone().add(dir),target);};
// Pause GPU work in background tabs.
document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(frameId);else{animationTime=performance.now();render(animationTime);}});
$('space').addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frameId);$('error').hidden=false;$('error').textContent='La connessione grafica è stata interrotta. Ricarica la pagina per riprendere l’esplorazione.'});
}
$('catalog-toggle').onclick=()=>{const open=$('catalog-body').hidden;$('catalog-body').hidden=!open;$('catalog-toggle').setAttribute('aria-expanded',open);document.querySelector('.plus').textContent=open?'−':'+';if(open){if(innerWidth<651&&selected)closeCard();$('search').focus();}};$('search').oninput=populateList;
const openMethod=()=>$('method').showModal();$('about').onclick=openMethod;$('sources').onclick=openMethod;$('close-method').onclick=()=>$('method').close();$('method').addEventListener('click',e=>{if(e.target===$('method')){const r=$('method').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('method').close();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selected)closeCard();});
init().catch(err=>{$('loading').hidden=true;$('error').hidden=false;$('error').textContent='Impossibile avviare la scena 3D. Verifica che WebGL sia disponibile e ricarica la pagina. Il catalogo resta scaricabile dalla sezione Fonti. '+err.message;console.error(err);});
